**NB - Regression**

In [1]:
# Import libraries

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error

import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv('C:/MAFAS/APU/CT046-3-M-AML/CT046 - LABS/Python LAB MATERIALS/Lab 4 - Naive Bayes/kc_house_data.csv')
data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [3]:
data.shape

(21613, 21)

In [4]:
# Drop unwanted variables
data = data.drop(['id', 'date', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long'], axis = 1)

In [5]:
data.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [6]:
# Descriptive statistics
data.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,sqft_living15,sqft_lot15
count,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1986.552492,12768.455652
std,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,685.391304,27304.179631
min,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,399.000000,651.000000
25%,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1490.000000,5100.000000
50%,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1840.000000,7620.000000
75%,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,2360.000000,10083.000000
max,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,6210.000000,871200.000000

In [7]:
# Detect missing values
data.isnull().sum()

price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [8]:
# Variable assingment
x = data.drop('price', axis = 1)
y = data['price']

In [9]:
y.head()

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64

In [10]:
# Data split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 42)

In [11]:
x_test[0:5]

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,sqft_living15,sqft_lot15
735,4,2.25,2070,8893,2.0,0,0,4,8,2070,0,2390,7700
2830,5,3.00,2900,6730,1.0,0,0,5,8,1830,1070,2370,6283
4106,4,2.50,3770,10893,2.0,0,2,3,11,3770,0,3710,9685
16218,3,3.50,4560,14608,2.0,0,2,3,12,4560,0,4050,14226
19964,3,2.50,2550,5376,2.0,0,0,3,9,2550,0,2250,4050

In [12]:
y_test.head()

735       365000.0
2830      865000.0
4106     1038000.0
16218    1490000.0
19964     711000.0
Name: price, dtype: float64

**MultinomialNB**

In [13]:
mnb = MultinomialNB()
mnb.fit(x_train, y_train)
y_pred = mnb.predict(x_test)

In [14]:
# MSE, RMSE, MAE

print("Mean Squared Error: ", round(mean_squared_error(y_test, y_pred), 2))
print('Root Mean Squared Error: ', round(root_mean_squared_error(y_test, y_pred), 2))
print('Mean Absolute Error: ', round(mean_absolute_error(y_test, y_pred), 2))

Mean Squared Error:  347329494750.49
Root Mean Squared Error:  589346.67
Mean Absolute Error:  345086.81

**GaussianNB**

In [15]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)
y_pred = gnb.predict(x_test)

In [16]:
# MSE, RMSE, MAE

print("Mean Squared Error: ", round(mean_squared_error(y_test, y_pred), 2))
print('Root Mean Squared Error: ', round(root_mean_squared_error(y_test, y_pred), 2))
print('Mean Absolute Error: ', round(mean_absolute_error(y_test, y_pred), 2))

Mean Squared Error:  94856716761.54
Root Mean Squared Error:  307988.18
Mean Absolute Error:  197877.57

**NOTE:**
* Feature scaling is NOT required for GaussianNB, but in practice, it is usually a very good idea.
* For General Regression Models (like Linear, Ridge, Lasso): Normalization is strongly recommended.
* Among the MultinomialNB and GaussianNB models, GaussianNB model is more suitable for regression problems. MultinomialNB model is more suitable for text classification problems.
* GaussianNB or MultinomialNB is a classification model, not a regression model. Choose a suitable regression model.
* No Hyperparameter tuning is required for both MultinomialNB and GaussianNB as they already smoothed models. 
* Hence, a Cross-Validation can be done to further validate the models.Cross-Validation techniques will be discuss in future sessions.

**Scoring Parameter**

See The scoring parameter: defining model evaluation rules for details. 

https://scikit-learn.org/stable/modules/model_evaluation.html

**K-Fold CV**

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html#sklearn.model_selection.KFold

The performance measure reported by K-Fold cross-validation is then the average of the values computed in the loop. This approach can be computationally expensive, but does not waste too much data (as is the case when fixing an arbitrary validation set), which is a major advantage in problems such as inverse inference where the number of samples is very small.

In [17]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold, cross_val_score
folds = KFold(n_splits = 5, shuffle = True, random_state = 42)
gnb = GaussianNB()
R2s_kcv = cross_val_score(gnb, x_train, y_train, cv = folds, scoring = 'neg_root_mean_squared_error')
print(R2s_kcv)
print("Average RMSE after K-Fold CV: ", np.mean(R2s_kcv))

[-283771.28005785 -284587.99910451 -287930.01435306 -310072.01522498
 -278428.66973658]
Average RMSE after K-Fold CV:  -288957.9956953967

**Repeated KFold**

In [18]:
from sklearn.model_selection import RepeatedKFold
rkfolds = RepeatedKFold(n_splits = 5, n_repeats = 5, random_state = 42)

R2s_rkcv = cross_val_score(gnb, x_train, y_train, cv = rkfolds, scoring = 'neg_root_mean_squared_error')
print(R2s_rkcv)
print("Average RMSE after Repeated K-Fold CV: ", np.mean(R2s_rkcv))

[-283771.28005785 -284587.99910451 -287930.01435306 -310072.01522498
 -278428.66973658 -297610.4809553  -296679.32968405 -294334.41147209
 -272806.27544409 -291257.39589001 -286798.84632389 -284965.40552297
 -319224.22292039 -296195.09739388 -282754.45104334 -287676.14177144
 -283782.50379864 -294933.4226467  -285523.97106075 -284153.29890218
 -284050.07147282 -311714.38388383 -277779.60384784 -293254.80566517
 -293416.11810596]
Average RMSE after Repeated K-Fold CV:  -290548.008651294