**ANN - Regression**

In [87]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Input, Dropout
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

In [88]:
# Reading data
data = pd.read_csv('C:/MAFAS/APU/CT046-3-M-AML/CT046 - LABS/Python LAB MATERIALS/Lab 9 - Neural Network/mart.csv')
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [89]:
data = data.drop(['Item_Identifier', 'Outlet_Identifier', 'Outlet_Establishment_Year', 'Outlet_Location_Type'], axis = 1)

In [90]:
data.dtypes

Item_Weight          float64
Item_Fat_Content      object
Item_Visibility      float64
Item_Type             object
Item_MRP             float64
Outlet_Size           object
Outlet_Type           object
Item_Outlet_Sales    float64
dtype: object

In [91]:
data.isnull().sum()

Item_Weight          1463
Item_Fat_Content        0
Item_Visibility         0
Item_Type               0
Item_MRP                0
Outlet_Size          2410
Outlet_Type             0
Item_Outlet_Sales       0
dtype: int64

In [92]:
# Assign variables
x = data.drop('Item_Outlet_Sales', axis = 1)
y = data['Item_Outlet_Sales']

In [93]:
# Data Split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [94]:
# Impute missing values for Item_Weight
Item_Weight_imputer = SimpleImputer(strategy = 'mean')
x_train['Item_Weight'] = Item_Weight_imputer.fit_transform(x_train[['Item_Weight']])
x_test['Item_Weight'] = Item_Weight_imputer.transform(x_test[['Item_Weight']])

In [95]:
# Impute missing values for Outlet_Size
Outlet_Size_imputer = SimpleImputer(strategy = 'most_frequent')
x_train['Outlet_Size'] = Outlet_Size_imputer.fit_transform(x_train[['Outlet_Size']]).ravel()
x_test['Outlet_Size'] = Outlet_Size_imputer.transform(x_test[['Outlet_Size']]).ravel()

In [96]:
x_train.isnull().sum()

Item_Weight         0
Item_Fat_Content    0
Item_Visibility     0
Item_Type           0
Item_MRP            0
Outlet_Size         0
Outlet_Type         0
dtype: int64

In [97]:
# Label Encoding for categorical variables
Item_Fat_Content_le = LabelEncoder()
Item_Fat_Content_le.fit(x_train['Item_Fat_Content'])
x_train['Item_Fat_Content'] = Item_Fat_Content_le.transform(x_train['Item_Fat_Content'])
x_test['Item_Fat_Content'] = Item_Fat_Content_le.transform(x_test['Item_Fat_Content'])

Item_Type_le = LabelEncoder()
x_train['Item_Type'] = Item_Type_le.fit_transform(x_train['Item_Type'])
x_test['Item_Type'] = Item_Type_le.transform(x_test['Item_Type'])

Outlet_Size_le = LabelEncoder()
x_train['Outlet_Size'] = Outlet_Size_le.fit_transform(x_train['Outlet_Size'])
x_test['Outlet_Size'] = Outlet_Size_le.transform(x_test['Outlet_Size'])

Outlet_Type_le = LabelEncoder()
x_train['Outlet_Type'] = Outlet_Type_le.fit_transform(x_train['Outlet_Type'])
x_test['Outlet_Type'] = Outlet_Type_le.transform(x_test['Outlet_Type'])

In [98]:
# Standardization
scaler = StandardScaler()
x_train = pd.DataFrame(scaler.fit_transform(x_train), columns = x_train.columns)
x_test = pd.DataFrame(scaler.transform(x_test), columns = x_test.columns)

In [99]:
x_train

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Size,Outlet_Type
0,-0.801383,0.973699,-0.600703,-0.302126,0.470709,-0.284198,-0.259489
1,1.210152,-0.571618,-0.362159,0.411711,0.457877,-0.284198,-0.259489
2,1.115491,0.973699,0.194933,0.649656,-0.482625,1.383325,-0.259489
3,-1.079448,-0.571618,-0.704944,-0.302126,-1.603553,-0.284198,-0.259489
4,-0.008602,-0.571618,1.383177,1.363492,0.218375,1.383325,-0.259489
...,...,...,...,...,...,...,...
6813,-0.826231,0.973699,4.282848,-0.302126,-0.043511,-0.284198,-1.509802
6814,0.642189,-0.571618,1.001006,-0.540071,-1.059078,-0.284198,-0.259489
6815,1.115491,-0.571618,-0.916931,0.173765,1.526207,-0.284198,-0.259489
6816,1.766282,2.519016,-0.228187,1.363492,-0.383072,-0.284198,-0.259489
6817,0.819677,-2.116934,-0.954859,0.411711,-0.738116,1.383325,-0.259489

**ANN Regressor - Base Model**

In [100]:
model = Sequential()
model.add(Input(shape = (7,))) # IL
model.add(Dense(units = 256, kernel_initializer = 'he_normal', activation = 'relu')) # HL1
model.add(Dropout(0.2))
model.add(Dense(units = 128, kernel_initializer = 'he_normal', activation = 'relu')) # HL2
model.add(Dropout(0.2))
model.add(Dense(units = 1, kernel_initializer = 'glorot_uniform', activation = 'linear')) # OL

model.compile(loss='mean_squared_error', optimizer = 'adam', metrics = ['mse'])

model.fit(x_train, y_train, validation_split = 0.1, batch_size = 16, epochs = 100)

Epoch 1/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 4493907.5000 - mse: 4493907.5000 - val_loss: 2124349.7500 - val_mse: 2124349.7500
Epoch 2/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1745988.1250 - mse: 1745988.1250 - val_loss: 1847251.8750 - val_mse: 1847251.8750
Epoch 3/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1627623.6250 - mse: 1627623.6250 - val_loss: 1768781.7500 - val_mse: 1768781.7500
Epoch 4/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1570603.5000 - mse: 1570603.5000 - val_loss: 1702350.2500 - val_mse: 1702350.2500
Epoch 5/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1516368.1250 - mse: 1516368.1250 - val_loss: 1636777.2500 - val_mse: 1636777.2500
Epoch 6/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1472755.8750 - mse: 1472755.8750 - val_loss: 1582271.0000 - val_mse: 1582271.0000
Epoch 7/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1437349.3750 - mse: 1437349.3750 - val_loss: 1551828.5000 - val_mse: 1551828.5000
Epoch 8/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1409727.3750 - mse: 1409727.3750 - val_loss: 1519487.1250 - val_mse: 1519487.1250
Epoch 9/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1398021.1250 - mse: 1398021.1250 - val_loss: 1503603.7500 - val_mse: 1503603.7500
Epoch 10/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1380995.3750 - mse: 1380995.3750 - val_loss: 1487287.8750 - val_mse: 1487287.8750
Epoch 11/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1360804.5000 - mse: 1360804.5000 - val_loss: 1473239.8750 - val_mse: 1473239.8750
Epoch 12/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1339337.3750 - mse: 1339337.3750 - val_loss: 1452214.3750 - val_mse: 1452214.3750
Epoch 13/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1349229.3750 - mse: 1349229.3750 - val_loss: 1450770.2500 - val_mse: 1450770.2500
Epoch 14/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1339321.3750 - mse: 1339321.3750 - val_loss: 1437974.6250 - val_mse: 1437974.6250
Epoch 15/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1321771.0000 - mse: 1321771.0000 - val_loss: 1426370.1250 - val_mse: 1426370.1250
Epoch 16/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1296658.8750 - mse: 1296658.8750 - val_loss: 1414549.1250 - val_mse: 1414549.1250
Epoch 17/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1291299.2500 - mse: 1291299.2500 - val_loss: 1416628.2500 - val_mse: 1416628.2500
Epoch 18/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1305439.1250 - mse: 1305439.1250 - val_loss: 1403957.6250 - val_mse: 1403957.6250
Epoch 19/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1295411.3750 - mse: 1295411.3750 - val_loss: 1403484.6250 - val_mse: 1403484.6250
Epoch 20/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1276700.7500 - mse: 1276700.7500 - val_loss: 1396490.8750 - val_mse: 1396490.8750
Epoch 21/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1297546.3750 - mse: 1297546.3750 - val_loss: 1392279.6250 - val_mse: 1392279.6250
Epoch 22/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1284741.3750 - mse: 1284741.3750 - val_loss: 1378257.0000 - val_mse: 1378257.0000
Epoch 23/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1288120.3750 - mse: 1288120.3750 - val_loss: 1378537.3750 - val_mse: 1378537.3750
Epoch 24/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1280948.1250 - mse: 1280948.1250 - val_loss: 1372349.6250 - val_mse: 1372349.6250
Epoch 25/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1271607.2500 - mse: 1271607.2500 - val_loss: 1377504.0000 - val_mse: 1377504.0000
Epoch 26/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1287698.7500 - mse: 1287698.7500 - val_loss: 1374413.1250 - val_mse: 1374413.1250
Epoch 27/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1286335.2500 - mse: 1286335.2500 - val_loss: 1372834.1250 - val_mse: 1372834.1250
Epoch 28/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1259523.6250 - mse: 1259523.6250 - val_loss: 1360843.5000 - val_mse: 1360843.5000
Epoch 29/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1273183.2500 - mse: 1273183.2500 - val_loss: 1359596.2500 - val_mse: 1359596.2500
Epoch 30/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1282787.7500 - mse: 1282787.7500 - val_loss: 1358692.1250 - val_mse: 1358692.1250
Epoch 31/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1273129.1250 - mse: 1273129.1250 - val_loss: 1369827.8750 - val_mse: 1369827.8750
Epoch 32/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1264856.7500 - mse: 1264856.7500 - val_loss: 1369041.6250 - val_mse: 1369041.6250
Epoch 33/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1268981.8750 - mse: 1268981.8750 - val_loss: 1364509.3750 - val_mse: 1364509.3750
Epoch 34/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1253062.5000 - mse: 1253062.5000 - val_loss: 1351034.3750 - val_mse: 1351034.3750
Epoch 35/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250404.5000 - mse: 1250404.5000 - val_loss: 1361408.7500 - val_mse: 1361408.7500
Epoch 36/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1254336.7500 - mse: 1254336.7500 - val_loss: 1349985.5000 - val_mse: 1349985.5000
Epoch 37/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1252338.6250 - mse: 1252338.6250 - val_loss: 1351143.5000 - val_mse: 1351143.5000
Epoch 38/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1259914.3750 - mse: 1259914.3750 - val_loss: 1353282.0000 - val_mse: 1353282.0000
Epoch 39/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1261665.7500 - mse: 1261665.7500 - val_loss: 1343185.5000 - val_mse: 1343185.5000
Epoch 40/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1268046.2500 - mse: 1268046.2500 - val_loss: 1366232.8750 - val_mse: 1366232.8750
Epoch 41/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1242636.6250 - mse: 1242636.6250 - val_loss: 1349818.7500 - val_mse: 1349818.7500
Epoch 42/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1237882.7500 - mse: 1237882.7500 - val_loss: 1341704.5000 - val_mse: 1341704.5000
Epoch 43/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250397.5000 - mse: 1250397.5000 - val_loss: 1343284.2500 - val_mse: 1343284.2500
Epoch 44/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1245998.1250 - mse: 1245998.1250 - val_loss: 1353337.2500 - val_mse: 1353337.2500
Epoch 45/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1252747.3750 - mse: 1252747.3750 - val_loss: 1341550.0000 - val_mse: 1341550.0000
Epoch 46/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1240660.1250 - mse: 1240660.1250 - val_loss: 1350207.0000 - val_mse: 1350207.0000
Epoch 47/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1233372.0000 - mse: 1233372.0000 - val_loss: 1351081.5000 - val_mse: 1351081.5000
Epoch 48/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1254649.6250 - mse: 1254649.6250 - val_loss: 1340903.7500 - val_mse: 1340903.7500
Epoch 49/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1246922.6250 - mse: 1246922.6250 - val_loss: 1349381.6250 - val_mse: 1349381.6250
Epoch 50/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1226559.5000 - mse: 1226559.5000 - val_loss: 1332960.1250 - val_mse: 1332960.1250
Epoch 51/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1243323.3750 - mse: 1243323.3750 - val_loss: 1345663.2500 - val_mse: 1345663.2500
Epoch 52/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250379.1250 - mse: 1250379.1250 - val_loss: 1347725.3750 - val_mse: 1347725.3750
Epoch 53/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248013.6250 - mse: 1248013.6250 - val_loss: 1333730.0000 - val_mse: 1333730.0000
Epoch 54/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1241261.8750 - mse: 1241261.8750 - val_loss: 1347194.0000 - val_mse: 1347194.0000
Epoch 55/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1255611.3750 - mse: 1255611.3750 - val_loss: 1344827.2500 - val_mse: 1344827.2500
Epoch 56/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1225359.2500 - mse: 1225359.2500 - val_loss: 1347655.5000 - val_mse: 1347655.5000
Epoch 57/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1229457.1250 - mse: 1229457.1250 - val_loss: 1343019.7500 - val_mse: 1343019.7500
Epoch 58/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1235320.8750 - mse: 1235320.8750 - val_loss: 1342013.5000 - val_mse: 1342013.5000
Epoch 59/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1241220.3750 - mse: 1241220.3750 - val_loss: 1347688.5000 - val_mse: 1347688.5000
Epoch 60/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1237845.7500 - mse: 1237845.7500 - val_loss: 1352274.7500 - val_mse: 1352274.7500
Epoch 61/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248821.6250 - mse: 1248821.6250 - val_loss: 1334185.2500 - val_mse: 1334185.2500
Epoch 62/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1226655.0000 - mse: 1226655.0000 - val_loss: 1349532.0000 - val_mse: 1349532.0000
Epoch 63/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1240449.7500 - mse: 1240449.7500 - val_loss: 1340071.5000 - val_mse: 1340071.5000
Epoch 64/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1236080.6250 - mse: 1236080.6250 - val_loss: 1338583.8750 - val_mse: 1338583.8750
Epoch 65/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1243530.3750 - mse: 1243530.3750 - val_loss: 1341321.0000 - val_mse: 1341321.0000
Epoch 66/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1234485.1250 - mse: 1234485.1250 - val_loss: 1337234.2500 - val_mse: 1337234.2500
Epoch 67/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1239121.7500 - mse: 1239121.7500 - val_loss: 1347237.5000 - val_mse: 1347237.5000
Epoch 68/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1236615.7500 - mse: 1236615.7500 - val_loss: 1344425.0000 - val_mse: 1344425.0000
Epoch 69/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1228197.1250 - mse: 1228197.1250 - val_loss: 1344038.6250 - val_mse: 1344038.6250
Epoch 70/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1241992.3750 - mse: 1241992.3750 - val_loss: 1331985.6250 - val_mse: 1331985.6250
Epoch 71/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1222146.8750 - mse: 1222146.8750 - val_loss: 1339627.1250 - val_mse: 1339627.1250
Epoch 72/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1234193.6250 - mse: 1234193.6250 - val_loss: 1338390.2500 - val_mse: 1338390.2500
Epoch 73/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1222355.2500 - mse: 1222355.2500 - val_loss: 1345382.2500 - val_mse: 1345382.2500
Epoch 74/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1237725.0000 - mse: 1237725.0000 - val_loss: 1342104.1250 - val_mse: 1342104.1250
Epoch 75/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1236781.7500 - mse: 1236781.7500 - val_loss: 1341767.0000 - val_mse: 1341767.0000
Epoch 76/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1233056.3750 - mse: 1233056.3750 - val_loss: 1333645.6250 - val_mse: 1333645.6250
Epoch 77/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1217667.7500 - mse: 1217667.7500 - val_loss: 1332693.8750 - val_mse: 1332693.8750
Epoch 78/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1229956.6250 - mse: 1229956.6250 - val_loss: 1339590.2500 - val_mse: 1339590.2500
Epoch 79/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1218993.8750 - mse: 1218993.8750 - val_loss: 1336776.8750 - val_mse: 1336776.8750
Epoch 80/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1222243.0000 - mse: 1222243.0000 - val_loss: 1347464.6250 - val_mse: 1347464.6250
Epoch 81/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1238902.6250 - mse: 1238902.6250 - val_loss: 1341151.3750 - val_mse: 1341151.3750
Epoch 82/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1229362.5000 - mse: 1229362.5000 - val_loss: 1331280.8750 - val_mse: 1331280.8750
Epoch 83/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1229633.6250 - mse: 1229633.6250 - val_loss: 1343625.6250 - val_mse: 1343625.6250
Epoch 84/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1218191.3750 - mse: 1218191.3750 - val_loss: 1339919.0000 - val_mse: 1339919.0000
Epoch 85/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1220925.1250 - mse: 1220925.1250 - val_loss: 1350022.3750 - val_mse: 1350022.3750
Epoch 86/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1229932.1250 - mse: 1229932.1250 - val_loss: 1349795.2500 - val_mse: 1349795.2500
Epoch 87/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1228090.2500 - mse: 1228090.2500 - val_loss: 1349675.1250 - val_mse: 1349675.1250
Epoch 88/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1211026.8750 - mse: 1211026.8750 - val_loss: 1339844.2500 - val_mse: 1339844.2500
Epoch 89/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1215436.8750 - mse: 1215436.8750 - val_loss: 1328602.1250 - val_mse: 1328602.1250
Epoch 90/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1206549.1250 - mse: 1206549.1250 - val_loss: 1342937.5000 - val_mse: 1342937.5000
Epoch 91/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1208194.8750 - mse: 1208194.8750 - val_loss: 1337697.7500 - val_mse: 1337697.7500
Epoch 92/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1217854.1250 - mse: 1217854.1250 - val_loss: 1329117.5000 - val_mse: 1329117.5000
Epoch 93/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1218925.5000 - mse: 1218925.5000 - val_loss: 1337240.8750 - val_mse: 1337240.8750
Epoch 94/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1200769.7500 - mse: 1200769.7500 - val_loss: 1337215.3750 - val_mse: 1337215.3750
Epoch 95/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1220839.7500 - mse: 1220839.7500 - val_loss: 1329975.5000 - val_mse: 1329975.5000
Epoch 96/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1213832.6250 - mse: 1213832.6250 - val_loss: 1337362.0000 - val_mse: 1337362.0000
Epoch 97/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1204344.0000 - mse: 1204344.0000 - val_loss: 1388653.3750 - val_mse: 1388653.3750
Epoch 98/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1219126.2500 - mse: 1219126.2500 - val_loss: 1340312.8750 - val_mse: 1340312.8750
Epoch 99/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1201939.2500 - mse: 1201939.2500 - val_loss: 1343959.6250 - val_mse: 1343959.6250
Epoch 100/100
384/384 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1204064.7500 - mse: 1204064.7500 - val_loss: 1339457.7500 - val_mse: 1339457.7500

In [101]:
y_pred = model.predict(x_test)

from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error
print('MSE:', round(mean_squared_error(y_pred, y_test),2))
print('RMSE:', round(root_mean_squared_error(y_pred, y_test),2))
print('R2:', round(r2_score(y_pred, y_test),2))

54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step
MSE: 1045669.39
RMSE: 1022.58
R2: 0.35

**Using Keras Tuner**

In [102]:
# %pip install keras-tuner

In [103]:
import keras_tuner as kt

def build_model(hp):
    model = Sequential()
    model.add(Input(shape = (7,))) # IL

    hp_units_1 = hp.Int('HL1', min_value = 16, max_value = 256, step = 4)
    hp_dropout_1 = hp.Float('Dropout1', min_value = 0.0, max_value = 0.5, step = 0.1)
    hp_units_2 = hp.Int('HL2', min_value = 16, max_value = 128, step = 4)
    hp_dropout_2 = hp.Float('Dropout2', min_value = 0.0, max_value = 0.5, step = 0.1)
    
    model.add(Dense(units = hp_units_1, activation = 'relu'))
    model.add(Dropout(hp_dropout_1))
    model.add(Dense(units = hp_units_2, activation = 'relu'))
    model.add(Dropout(hp_dropout_2))
    model.add(Dense(1, activation = 'linear'))
    
    hp_optimizer = hp.Choice('Optimizer', ['sgd', 'adam', 'rmsprop'])
    
    model.compile(optimizer = hp_optimizer, loss = 'mean_squared_error', metrics = ['mse'])
    return model

tuner = kt.RandomSearch(build_model, objective = 'val_mse', max_trials = 5, overwrite = True)

tuner.search(x_train, y_train, validation_split = 0.1, epochs = 100, batch_size = 16)

Trial 5 Complete [00h 00m 39s]
val_mse: nan

Best val_mse So Far: 1355054.25
Total elapsed time: 00h 03m 24s

In [104]:
for h_param in ["HL1", "Dropout1", "HL2", "Dropout2", "Optimizer"]:
    print(h_param, tuner.get_best_hyperparameters()[0].get(h_param))

HL1 196
Dropout1 0.1
HL2 48
Dropout2 0.4
Optimizer adam

In [105]:
tuner.results_summary(num_trials = 5)

Results summary
Results in .\untitled_project
Showing 5 best trials
Objective(name="val_mse", direction="min")

Trial 1 summary
Hyperparameters:
HL1: 196
Dropout1: 0.1
HL2: 48
Dropout2: 0.4
Optimizer: adam
Score: 1355054.25

Trial 3 summary
Hyperparameters:
HL1: 56
Dropout1: 0.1
HL2: 20
Dropout2: 0.1
Optimizer: adam
Score: 1399663.0

Trial 0 summary
Hyperparameters:
HL1: 56
Dropout1: 0.30000000000000004
HL2: 20
Dropout2: 0.2
Optimizer: adam
Score: 1566065.0

Trial 2 summary
Hyperparameters:
HL1: 248
Dropout1: 0.2
HL2: 100
Dropout2: 0.30000000000000004
Optimizer: sgd
Score: nan

Trial 4 summary
Hyperparameters:
HL1: 160
Dropout1: 0.30000000000000004
HL2: 80
Dropout2: 0.4
Optimizer: sgd
Score: nan

**Final Model**

In [106]:
best_model = tuner.get_best_models(num_models = 1)[0]

c:\Users\raheem\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [107]:
y_pred_f = best_model.predict(x_test)

from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error
print('MSE:', round(mean_squared_error(y_pred_f, y_test),2))
print('RMSE:', round(root_mean_squared_error(y_pred_f, y_test),2))
print('R2:', round(r2_score(y_pred_f, y_test),2))

54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
MSE: 1067130.76
RMSE: 1033.02
R2: 0.32